services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: adi@123
      MYSQL_DATABASE: mysql-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: adi@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  wordpress-web:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306 
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: adi@123
      WORDPRESS_DB_NAME: mysql-db
    ports:
      - "8081:80"
    depends_on:
      mysql-db:
        condition: service_healthy


volumes:
  db_data:
